### ISSUE TITLE
cli: `popper run` fails in Git repo without commits

### ISSUE THREAD

**Issue by wtraylor** [getpopper/popper#848]
# Steps to reproduce
```bash
git init myrepo
cd myrepo
popper scaffold
popper run -f wf.yml
```
Error message:
```
Traceback (most recent call last):
  File "/home/living/.local/bin/popper", line 8, in <module>
    sys.exit(cli())
  File "/home/living/.local/popper/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/living/.local/popper/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/living/.local/popper/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/living/.local/popper/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/living/.local/popper/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/living/.local/popper/lib/python3.8/site-packages/click/decorators.py", line 73, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "/home/living/.local/popper/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/living/.local/popper/lib/python3.8/site-packages/popper/commands/cmd_run.py", line 169, in cli
    config = ConfigLoader.load(
  File "/home/living/.local/popper/lib/python3.8/site-packages/popper/config.py", line 52, in load
    "git_commit": scm.get_sha(repo),
  File "/home/living/.local/popper/lib/python3.8/site-packages/popper/scm.py", line 173, in get_sha
    return repo.git.rev_parse(repo.head.object.hexsha)
  File "/home/living/.local/popper/lib/python3.8/site-packages/git/refs/symbolic.py", line 190, in _get_object
    return Object.new_from_sha(self.repo, hex_to_bin(self.dereference_recursive(self.repo, self.path)))
  File "/home/living/.local/popper/lib/python3.8/site-packages/git/refs/symbolic.py", line 132, in dereference_recursive
    hexsha, ref_path = cls._get_ref_info(repo, ref_path)
  File "/home/living/.local/popper/lib/python3.8/site-packages/git/refs/symbolic.py", line 181, in _get_ref_info
    return cls._get_ref_info_helper(repo, ref_path)
  File "/home/living/.local/popper/lib/python3.8/site-packages/git/refs/symbolic.py", line 164, in _get_ref_info_helper
    raise ValueError("Reference at %r does not exist" % ref_path)
ValueError: Reference at 'refs/heads/master' does not exist
```

- Popper version: Current `master`, in virtual environment with Python 3.8.3
- Git version: 2.27.0
- Operating system: Arch Linux

# Expected behavior
An error message that Popper needs an initial commit, or ignore that we are in a Git repository.

**Comment by JayjeetAtGithub** [comment]
Thanks for reporting @wtraylor . We will push a fix soon.

**Comment by ivotron** [comment]
thanks a lot for the detailed report @wtraylor ! For this we need to modify the [`cli/popper/scm.py`](https://github.com/getpopper/popper/blob/0bb2306/cli/popper/commands/cmd_run.py)

**Comment by JayjeetAtGithub** [comment]
I would like to work in this @ivotron .
