### ISSUE TITLE
Allow Git remote that’s not named “origin”

### ISSUE THREAD

**Issue by wtraylor** [getpopper/popper#896]
# Steps to Reproduce

Popper version: Latest `master`, commit 227bfeeb545aa83c6960ccffdb374c783ae58c68
```bash
# Create a dummy repo serving as remote.
git init upstream
cd upstream
popper scaffold
git add wf.yml
git commit -m 'Add scaffold'

# Create downstream whose remote is not called “origin”
cd ..
git clone ./upstream --origin upstream local
cd local
popper run -f wf.yml
```

This creates an error message:
```
Traceback (most recent call last):
  File "/home/living/.local/bin/popper", line 8, in <module>
    sys.exit(cli())
  File "/home/living/.local/popper/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/living/.local/popper/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/living/.local/popper/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/living/.local/popper/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/living/.local/popper/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/living/.local/popper/lib/python3.8/site-packages/click/decorators.py", line 73, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "/home/living/.local/popper/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/living/.local/popper/lib/python3.8/site-packages/popper/commands/cmd_run.py", line 181, in cli
    config = ConfigLoader.load(
  File "/home/living/.local/popper/lib/python3.8/site-packages/popper/config.py", line 59, in load
    "git_remote_origin_url": scm.get_remote_url(repo),
  File "/home/living/.local/popper/lib/python3.8/site-packages/popper/scm.py", line 41, in get_remote_url
    url = repo.remotes.origin.url
  File "/home/living/.local/popper/lib/python3.8/site-packages/git/util.py", line 873, in __getattr__
    return list.__getattribute__(self, attr)
AttributeError: 'IterableList' object has no attribute 'origin'
```

# Suggested Solution
It’s the function `get_remote_url()` in `src/popper/scm.py` that’s causing trouble:
```python
def get_remote_url(repo=None):
    url = ""
    if repo:
        if len(repo.remotes) > 0:
            url = repo.remotes.origin.url
        # cleanup the URL so we get in in https form and without '.git' ending
        if url.endswith(".git"):
            url = url[:-4]
        if "git@" in url:
            url = "https://" + url[4:].replace(":", "/")
    return url
```
I guess a simple check if `origin` is member of `repo.remotes` should fix it. But a remote not named “origin” should also be recognized, I guess.

**Comment by ivotron** [comment]
thanks for reporting this @wtraylor!

> I guess a simple check if `origin` is member of `repo.remotes` should fix it.

That's right, this should check first if `origin` is part of the list of remotes.

> But a remote not named “origin” should also be recognized, I guess.

The main issue is that names of remotes is arbitrary, although `upstream` is pretty common. One alternative could be to create a `GIT_REMOTE_URL_LIST` that contains a comma-separated list of all remotes available for that git repo. what do you think?
