### ISSUE TITLE
exporter: error while running popper translate

### ISSUE THREAD

**Issue by JayjeetAtGithub** [getpopper/popper#977]
```
(venv) noobjc@node0:~/popper$ popper 
Traceback (most recent call last):
  File "/users/noobjc/popper/venv/bin/popper", line 11, in <module>
    load_entry_point('popper==0.0.0', 'console_scripts', 'popper')()
  File "/users/noobjc/popper/venv/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/users/noobjc/popper/venv/lib/python3.8/site-packages/click/core.py", line 781, in main
    with self.make_context(prog_name, args, **extra) as ctx:
  File "/users/noobjc/popper/venv/lib/python3.8/site-packages/click/core.py", line 700, in make_context
    self.parse_args(ctx, args)
  File "/users/noobjc/popper/venv/lib/python3.8/site-packages/click/core.py", line 1209, in parse_args
    echo(ctx.get_help(), color=ctx.color)
  File "/users/noobjc/popper/venv/lib/python3.8/site-packages/click/core.py", line 570, in get_help
    return self.command.get_help(self)
  File "/users/noobjc/popper/venv/lib/python3.8/site-packages/click/core.py", line 975, in get_help
    self.format_help(ctx, formatter)
  File "/users/noobjc/popper/venv/lib/python3.8/site-packages/click/core.py", line 1003, in format_help
    self.format_options(ctx, formatter)
  File "/users/noobjc/popper/venv/lib/python3.8/site-packages/click/core.py", line 1137, in format_options
    self.format_commands(ctx, formatter)
  File "/users/noobjc/popper/venv/lib/python3.8/site-packages/click/core.py", line 1185, in format_commands
    cmd = self.get_command(ctx, subcommand)
  File "/users/noobjc/popper/venv/lib/python3.8/site-packages/popper/cli.py", line 65, in get_command
    cmd_mod = importlib.import_module(cmd_path)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/users/noobjc/popper/venv/lib/python3.8/site-packages/popper/commands/cmd_translate.py", line 6, in <module>
    from popper.translators.translator import WorkflowTranslator
ModuleNotFoundError: No module named 'popper.translators'
```

**Comment by JayjeetAtGithub** [comment]
@shumbo I am getting this error while running popper from the `popper-to-drone` branch. Can you please take a look ?
